version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "voice-foundry"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dssyr49jt5yk"
s3_prefix = "voice-foundry"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
